

@URL = http://localhost:3001
@json = Content-Type: application/json



### 测试 管理员
get {{URL}}/api/admin

### 管理员注册     管理员注册接口在admin.js 第一个路由
post {{URL}}/api/admin/register
{{json}}

{
    "email":"  请填写邮箱  ",
    "password":"  请填写密码  ",
    "username":" 请设置名字  "
}

### 管理员登录
post {{URL}}/api/admin/login
{{json}}

{
    "email":"  你的邮箱  ",
    "password":"   你的密码   "
}

### 获取所有用户
get {{URL}}/api/admin/allmessage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkMGI2ZjgzYjc0NzEwMzJlY2U1NDc2NyIsImVtYWlsIjoiYWRtaW5AMTYzLmNvbSIsInVzZXJuYW1lIjoi566h55CG5ZGYMSIsImRhdGUiOiIyMDE5LzA2LzIwIDE5OjM1OjMxIiwiaWF0IjoxNTYxMDQzOTIzLCJleHAiOjE1NjEwNDc1MjN9.rWTC0BB8zMNE8uHl9Cyw9nlRvO2lwt5LSNa-4eXXdLM